### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [usehero/hero-ecommerce-tracking-gtm-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation link [https://github.com/usehero/hero-ecommerce-tracking-gtm-template](https://github.com/usehero/hero-ecommerce-tracking-gtm-template) provided in the manifest redirects user to the Github page. It does not provide any information regarding the template

![Screenshot 2020-07-21 at 12 27 49 PM](https://user-images.githubusercontent.com/53495700/88097800-9ae76e00-cb4d-11ea-907b-db4ce12d6d36.png)

2) When we try to run sample test on the template, an error "An unknown error has occurred, please try again." is shown in the console.
![Screenshot 2020-07-21 at 12 29 00 PM](https://user-images.githubusercontent.com/53495700/88097944-d2561a80-cb4d-11ea-8163-70b619fbe38d.png)

**Comment by hero-oss-dev** [comment]
Hi @praveena-pappu. Thanks for your feedback! I have updated the project README.md file to include instructions on how to add, configure and save the tag.

I'm not sure why you are seeing an error on that page. Are you referencing a variable that does not exist?

You can see that I am able to successfully run the tag within my workspace:

![Screenshot 2020-07-22 at 17](https://user-images.githubusercontent.com/68552498/88203052-a025e500-cc41-11ea-8041-913d3c80bb6d.jpg)
